//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public bool PaymentType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsPic { get; set; }
        public string PicUrl { get; set; }
        public Nullable<int> TUserId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> MethodId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Method Method { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
