//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CreateMonth { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TUserId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
