//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUser()
        {
            this.Bill = new HashSet<Bill>();
            this.Budget = new HashSet<Budget>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string PhoneNum { get; set; }
        public string Email { get; set; }
        public string Abode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> IsPic { get; set; }
        public string PicUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budget { get; set; }
    }
}
